-- Enable required extension for gen_random_uuid()
create extension if not exists pgcrypto;

-- Subscribers with unsubscribe + geolocation
create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  unsubscribed boolean not null default false,
  unsubscribed_at timestamp with time zone,
  city text,
  region text,
  country text,
  timezone text,
  ip text,
  created_at timestamp with time zone default now()
);

-- Campaigns to log granular sends
create table if not exists public.newsletter_campaigns (
  id bigint generated by default as identity primary key,
  subject text not null,
  story_slugs jsonb not null,
  subscriber_emails jsonb,
  created_at timestamp with time zone default now()
);

-- Per-email logs referencing optional campaign
create table if not exists public.newsletter_logs (
  id bigint generated by default as identity primary key,
  email text not null,
  status text not null,
  detail text,
  type text default 'bulk', -- 'bulk' | 'welcome'
  campaign_id bigint references public.newsletter_campaigns(id) on delete set null,
  story_slugs jsonb,
  created_at timestamp with time zone default now()
);

-- Helpful indexes
create index if not exists idx_newsletter_logs_created_at on public.newsletter_logs(created_at desc);
create index if not exists idx_newsletter_subscribers_email on public.newsletter_subscribers(email);
